apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/test/test-script.js"]
          volumeMounts:
            - name: k6-script
              mountPath: /test
      restartPolicy: Never
      volumes:
        - name: k6-script
          configMap:
            name: k6-test-script
  backoffLimit: 1